/** Search presets for Openverse (CC0 / public domain only). */
export const FLAIR_QUERIES = {
  fruit: [
    'apple fruit clipart transparent',
    'banana fruit icon',
    'orange fruit illustration',
    'strawberry fruit clipart',
    'grape fruit icon',
    'watermelon fruit illustration',
    'pineapple fruit clipart',
    'lemon fruit icon',
    'cherry fruit clipart',
    'pear fruit illustration',
    'mango fruit clipart',
    'kiwi fruit illustration',
    'peach fruit sticker',
    'blueberry fruit icon',
    'coconut fruit clipart',
  ],
  object: [
    'star icon png transparent',
    'heart icon png',
    'cloud png transparent',
    'lightning bolt png',
    'flower png transparent',
    'leaf png transparent',
    'moon png icon',
    'sun png icon',
    'balloon png clipart',
    'gift box png sticker',
    'camera png vintage',
    'book png illustration',
  ],
  symbol: [
    'diamond gem png',
    'crown icon png',
    'trophy icon png',
    'bell icon png',
    'shield icon png',
    'sword icon png',
    'anchor icon png',
    'compass icon png',
  ],
  character: [
    'ghost cartoon png sticker',
    'robot cartoon png transparent',
    'alien cartoon png clipart',
    'skull cartoon png sticker',
    'cat cartoon png transparent',
    'dog cartoon png sticker',
    'bunny cartoon png',
    'bear cartoon png clipart',
    'fox cartoon png sticker',
    'owl cartoon png',
    'penguin cartoon png',
    'frog cartoon png sticker',
    'dragon cartoon png clipart',
    'unicorn cartoon png',
    'fairy cartoon png sticker',
    'wizard cartoon png',
    'witch cartoon png clipart',
    'vampire cartoon png',
    'zombie cartoon png sticker',
    'skeleton cartoon png',
    'pirate cartoon png clipart',
    'ninja cartoon png sticker',
    'knight cartoon png',
    'princess cartoon png clipart',
    'superhero cartoon png sticker',
    'villain cartoon png',
    'clown cartoon png clipart',
    'mermaid cartoon png',
    'monster cartoon png sticker',
    'devil cartoon png clipart',
    'angel cartoon png',
    'astronaut cartoon png sticker',
    'cowboy cartoon png',
    'samurai cartoon png clipart',
    'robot mascot png',
    'game mascot png sticker',
    'pixel character png',
    'retro game character png',
    'arcade character png clipart',
  ],
  /** Recognizable names / archetypes — only CC0/PD results from Openverse. */
  character_ip: [
    'mickey mouse vintage illustration',
    'steamboat willie cartoon',
    'sherlock holmes illustration vintage',
    'alice wonderland illustration',
    'frankenstein monster illustration',
    'dracula vintage illustration',
    'peter pan illustration vintage',
    'wizard of oz illustration',
    'robin hood illustration vintage',
    'pinocchio vintage illustration',
    'cinderella vintage illustration',
    'red riding hood illustration',
    'three little pigs illustration',
    'humpty dumpty illustration',
    'alice in wonderland caterpillar',
    'cheshire cat illustration vintage',
    'mad hatter illustration',
    'white rabbit illustration vintage',
    'nutcracker illustration vintage',
    'scrooge illustration vintage',
    'tiny tim illustration',
    'moby dick whale illustration',
    'captain nemo illustration',
    'tarzan illustration vintage',
    'mowgli jungle book illustration',
    'hercules mythology illustration',
    'medusa mythology illustration',
    'pegasus illustration vintage',
    'centaur mythology illustration',
    'phoenix bird illustration',
    'griffin mythology illustration',
    'dragon chinese illustration vintage',
    'sun wukong illustration',
    'journey west monkey king',
    'spider man vintage comic clipart',
    'batman vintage comic illustration',
    'superman vintage comic illustration',
    'wonder woman vintage comic',
    'captain america vintage comic',
    'iron man cartoon clipart',
    'hulk cartoon illustration',
    'thor mythology cartoon',
    'flash superhero vintage',
    'green lantern vintage comic',
    'x-men vintage comic illustration',
    'fantastic four vintage comic',
    'ninja turtles vintage cartoon',
    'power rangers style cartoon',
    'pokemon style monster clipart',
    'mario style plumber cartoon',
    'sonic style hedgehog cartoon',
    'link style hero cartoon clipart',
    'kirby style character clipart',
    'donkey kong vintage illustration',
    'pac-man character clipart',
    'space invader character png',
    'megaman style robot clipart',
    'street fighter character clipart',
    'mortal kombat character clipart',
    'disney princess vintage illustration',
    'sleeping beauty illustration vintage',
    'snow white illustration vintage',
    'beauty beast illustration vintage',
    'little mermaid illustration vintage',
    'lion king style lion clipart',
    'finding nemo fish clipart',
    'toy story cowboy clipart',
    'buzz lightyear style astronaut clipart',
    'shrek ogre cartoon clipart',
    'minions style character clipart',
    'simpsons style cartoon family',
    'spongebob style sea character clipart',
    'patrick star style cartoon clipart',
    'rick and morty style scientist clipart',
    'adventure time style character clipart',
    'steven universe style character clipart',
    'gravity falls character clipart',
    'avatar last airbender style clipart',
    'naruto style ninja clipart',
    'goku style fighter clipart',
    'sailor moon style character clipart',
    'hello kitty style cat clipart',
    'snoopy dog illustration vintage',
    'garfield cat cartoon clipart',
    'calvin hobbes style cartoon clipart',
    'peanuts charlie brown illustration',
    'betty boop vintage illustration',
    'felix the cat vintage illustration',
    'popeye sailor illustration vintage',
    'bugs bunny style rabbit clipart',
    'daffy duck style cartoon clipart',
    'tom and jerry style cartoon clipart',
    'scooby doo dog cartoon clipart',
    'flintstones cartoon family clipart',
    'jetsons cartoon family clipart',
    'yogi bear cartoon clipart',
    'smurf cartoon character clipart',
    'care bears cartoon clipart',
    'my little pony style clipart',
    'transformers robot vintage clipart',
    'g.i. joe soldier cartoon clipart',
    'he-man cartoon clipart',
    'thundercats cartoon clipart',
    'voltron robot clipart',
    'robocop style robot clipart',
    'terminator robot clipart',
    'star wars droid clipart vintage',
    'darth vader helmet clipart',
    'yoda style character clipart',
    'stormtrooper helmet clipart',
    'mandalorian helmet clipart',
    'baby yoda style character clipart',
    'harry potter wizard clipart',
    'hermione style witch clipart',
    'dobby elf clipart',
    'lord rings hobbit clipart',
    'gollum character clipart',
    'gandalf wizard clipart',
    'dragon ball character clipart',
    'one piece pirate clipart',
    'demon slayer character clipart',
    'jojo character clipart',
    'evangelion robot clipart',
    'totoro style creature clipart',
    'kiki delivery service witch clipart',
    'howl moving castle character clipart',
    'wall-e robot clipart',
    'buzz woody cartoon clipart',
    'elsa ice princess clipart',
    'moana character clipart',
    'encanto character clipart',
    'coco skeleton musician clipart',
    'inside out emotion character clipart',
    'up movie balloon house clipart',
    'walle eve robot clipart',
  ],
}

export const ALL_FLAIR_QUERIES = Object.values(FLAIR_QUERIES).flat()

export const OPENVERSE_LICENSES = 'cc0,pdm'
export const OPENVERSE_API = 'https://api.openverse.org/v1/images/'

export const inferCategory = (query) => {
  if (FLAIR_QUERIES.fruit.includes(query)) return 'fruit'
  if (FLAIR_QUERIES.character.includes(query) || FLAIR_QUERIES.character_ip.includes(query)) {
    return 'character'
  }
  if (FLAIR_QUERIES.symbol.includes(query)) return 'symbol'
  if (FLAIR_QUERIES.object.includes(query)) return 'object'
  return 'character'
}
